openapi: 3.1.0
info:
  title: Leer celda F22
  description: Devuelve el valor de la celda G21 de una hoja de cálculo
  version: 1.0.0
servers:
  - url: https://script.google.com/macros/s/AKfycbwYalcDtuJOmrJPqadaQRoN8UBfuJAZd9HrQ0QS3pL3gv1Aechzxffoov6dKfNeRQy4/exec
paths:
  /:
    get:
      operationId: leerValorF22
      summary: Leer el contenido de la celda F22
      parameters: []
      responses:
        '200':
          description: Valor de la celda F22
          content:
            application/json:
              schema:
                type: object
                properties:
                  resultado:
                    type: number
                    description: Valor leído desde F22
