openapi: 3.1.0
info:
  title: Leer celda F22
  description: Devuelve el valor de la celda F22 de una hoja de cálculo
  version: 1.0.0
servers:
  - url: https://script.google.com/macros/s/AKfycbyneaPDeVRUCsIgVUtvM-2pNtirv5JKMqJpdkEXvyh6KW2P0ZJDwxOplei8b5l6XU7SBw/exec
paths:
  /:
    get:
      operationId: leerValorF22
      summary: Leer el contenido de la celda F22
      parameters: []
      responses:
        "200":
          description: Valor de la celda F22
          content:
            text/plain:
              schema:
                type: string
